version: "2"
linters:
  default: all
  disable:
    - wsl
    - revive
    - ireturn
    - depguard
    - exhaustruct
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  go: '1.25.5'
