on: [ push, pull_request ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.5"
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.7.2
          install-only: true
      - name: check format
        run: golangci-lint fmt --diff

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.5"
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.7.2
